name: Publish to PyPI

on:
  push:
    branches: "*"
    tags: ["*"]

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: create a distribution
      run: |
        pip3 install build wheel
        python3 -m build --wheel
    - run: |
        ls dist
        unzip dist/torch_dftd-0.5.0-py3-none-any.whl
        ls dist
    # - name: Publish package distributions to PyPI
    #   uses: pypa/gh-action-pypi-publish@release/v1
