name: Publish to PyPI

on:
  push:
    tags: ["*"]

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/torch-dftd
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: create a distribution
      run: |
        pip3 install build wheel
        python3 -m build --wheel
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
